### ISSUE TITLE
Deployment problem on a R/Shiny Server Pro

### ISSUE THREAD

**Issue by wyu** [SlavovLab/DO-MS#2]
Thanks so much for this wonderful tool! 

We're getting some error after deploying it on our Shiny Server Pro server on a Redhat machine. I had to manually install all the packages on your dependency list. The page would get render and then got disconnected. 

The error message in my Javascript console seems to suggest a problem with SockJS connection. 

The same deployment on my Mac went perfectly without problem.
<img width="535" alt="Screen Shot 2019-07-26 at 11 46 45 AM" src="https://user-images.githubusercontent.com/760649/61967791-e51a2b80-af9b-11e9-9389-64fa0397bd3f.png">

Thanks!
wen

**Comment by blahoink** [comment]
Hi Wen, thanks for the report.

We don't have a Shiny Server Pro license but I will see if I can get our school's IT department to set one up for us so I can look into this issue.

One potential issue with compatibility with shiny server pro is that DO-MS needs access to the server filesystem in order to import data (user uploads over http are now built into the app right now). 

I haven't tried it, but maybe a less-managed configuration, like an R instance running on the command-line, would work better.

**Comment by wyu** [comment]
Thanks for your quick reply! I've actually solved my own question. It's indeed due to the file access problem. Here are the Dx info in case other people has the same issue.

# on the server where the R/Shiny Pro server is located. Make sure you have the following lines in /etc/shiny-server/shiny-server.conf

sanitize_errors off;disable_protocols xdr-streaming xhr-streaming iframe-eventsource iframe-htmlfile;
preserve_logs true;

After the failure, I received the following error message in "/var/log/shiny-server/DO-MS-1.0.9-shiny-20190726-173839-39638.log"

more DO-MS-1.0.9-shiny-20190726-173334-45440.log

Listening on http://127.0.0.1:45440
Warning in open.connection(path, "wb") :
  cannot open file 'folder_list.txt': Permission denied
Warning: Error in open.connection: cannot open the connection
  49: open.connection
  47: stream_delim
  46: write_delim
  45: write_tsv
  44: <observer> [/mnt/rbxdata1/shinyapps/contrib/DO-MS-1.0.9/server.R#166]
   1: runApp

The solution is to make sure the folder where the DO-MS app is deployed is writable by the Shiny server itself.

**Comment by blahoink** [comment]
Great! Just a note - you will have to make your data files accessible via. filesystem by the DO-MS server as we don't have http uploads. This can be done via. ftp or a network drive if available. While this isn't a problem on normal, self-hosted DO-MS instances (as client and server share the same filesystem), this distinction is important when you're running this on a dedicated server.
