### ISSUE TITLE
Shiny app is not starting up

### ISSUE THREAD

**Issue by Maithy15** [SlavovLab/DO-MS#24]
Hi,

When I try to run the app, I get the following error.

[1] "pandoc could not be found in default directories. If it is not available on the system PATH then PDF report generation will fail."
[1] "Checking online for latest version of DO-MS..."
[1] "You are on the latest version of DO-MS: 2.0.6"
[1] "DO-MS mode: dia-nn found in settings.yaml"
Error in init() : object 'source_file' not found

Please let me know how ot fix it.

Thanks
Maithy

**Comment by KevinMcDonnell6** [comment]
Hi Maithy, I had the same issue. I resolved it by defining the variable `source_file` in the module "modules/dia-nn/020_Ion_Sampling/instrument_17_DIA_MS1_counts.R".

**Comment by Maithy15** [comment]
Thanks! I will try and let you know.

**Comment by cjvonbuehler** [comment]
Hi Kevin,

I have the same problem as Maithy. Could you give me a hint how exactly you defined the variabel? Unfortunately, I did not get it how to modify the file you were mentioning.
Thanks, Clemens.

**Comment by KevinMcDonnell6** [comment]
So I defined it at the beginning of the file, as below. I'm not sure if the string itself matters all that much.
`init <- function() {
  
  type <- 'plot'
  box_title <- 'Channel-wise MS1 Copy Number for Precursors'
  help_text <- 'Plotting the MS1 copy numbers for all precursors associated with one of the defined channels. The copy numbers are calculated using the signal-to-noise ratio as described in Derks et al. 2022. By default, a resolution of 70,000 is used during preprocessing. It can be changed with the –resolution parameter.'
  source_file <- 'report'`

**Comment by cjvonbuehler** [comment]
Thanks a lot! That did the trick. :-)

**Comment by Maithy15** [comment]
I thank you all very much for your help!
