### ISSUE TITLE
mistake in global.R

### ISSUE THREAD

**Issue by KanshinED1** [SlavovLab/DO-MS#6]
Hi guys, in the latest DO-MS version in the global.R you have the following lines:
# check R version. required R >= 3.5.0
if(as.numeric(R.Version()$minor) < 5) {
  stop('R Version >= 3.5.0 required. Download the latest version of R from the CRAN page: https://cran.r-project.org/')
}

You have to change from 5 to 0.1 since I have R v 4.0.3 and it didn't work until I made a change. Take into account that the current R version is 4.0.... and it although it is newer than 3.5 it won't satisfy your criteria.

**Comment by GrayHuffman** [comment]
Thanks for writing us, @KanshinED1! I'd fixed this in our local version, but hadn't pushed it to GitHub, yet. Will update right now!
