### ISSUE TITLE
Error when running the app for the first time

### ISSUE THREAD

**Issue by armonyG** [SlavovLab/DO-MS#9]
I just downloaded Do-MS and ran the app from `server.R`.
A page opens and says:
**An error has occurred!**
object of type 'closure' is not subsettable
while the console says:
```
> runApp()
[1] "Checking online for latest version of DO-MS..."
[1] "You are on the latest version of DO-MS: 1.0.9"

Listening on http://127.0.0.1:4574
Warning: Error in <-: object of type 'closure' is not subsettable
  [No stack trace available]
Warning: Error in <-: object of type 'closure' is not subsettable
  [No stack trace available]

```
 - OS: windows 10 (10.0.19041 Build 19041)
 - Browser: Firefox 85.0 (64-bit)

Other than installing the dependencies, is there something else i should do before I can launch the app?

**Comment by xqyn** [comment]
> I just downloaded Do-MS and ran the app from `server.R`.
> A page opens and says:
> **An error has occurred!**
> object of type 'closure' is not subsettable
> while the console says:
> 
> ```
> > runApp()
> [1] "Checking online for latest version of DO-MS..."
> [1] "You are on the latest version of DO-MS: 1.0.9"
> 
> Listening on http://127.0.0.1:4574
> Warning: Error in <-: object of type 'closure' is not subsettable
>   [No stack trace available]
> Warning: Error in <-: object of type 'closure' is not subsettable
>   [No stack trace available]
> ```
> 
> * OS: windows 10 (10.0.19041 Build 19041)
> * Browser: Firefox 85.0 (64-bit)
> 
> Other than installing the dependencies, is there something else i should do before I can launch the app?

Hi armonyG, they have just upload new server.R yesterday. It works for me. You should try
